// Generated by `npx @cmssy/cli types` from the "cmssy-demo" workspace.
// Do not edit: change the model in the CMS and run the command again.

/** A translatable field: one string, or one per enabled language. */
export type CmssyLocalized = string | Record<string, string>;

/** What a media field holds. Mirrors `MediaFieldValue` in @cmssy/types. */
export type CmssyMedia = string;

/** What a file field holds. Mirrors `FileFieldValue` in @cmssy/types. */
export type CmssyFile = string;

/** A record as `public.model.records` returns it, with `data` typed. */
export interface CmssyRecordOf<Data> {
  id: string;
  modelId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  data: Data;
}

/**
 * Category
 *
 * Product categories for the MACHTEC industrial catalog.
 *
 * Model slug: `category`
 * Display field: `name`
 */
export interface CategoryData {
  /** Name */
  name: CmssyLocalized;
  /** Slug */
  slug: string;
  /** Code - Short catalog code, e.g. BRG */
  code?: string;
  /** Description */
  description?: CmssyLocalized;
  /** Image */
  image?: CmssyMedia;
  /** Sort order */
  sortOrder?: number;
}

export type CategoryRecord = CmssyRecordOf<CategoryData>;

/**
 * Product
 *
 * Industrial parts catalog for the MACHTEC demo shop. Prices are net, in minor units (cents).
 *
 * Model slug: `product`
 * Display field: `title`
 */
export interface ProductData {
  /** Title */
  title: CmssyLocalized;
  /** Slug */
  slug: string;
  /** SKU */
  sku: string;
  /** Brand */
  brand?: string;
  /** Category - Record id(s) from `category`. */
  category?: string;
  /** Description */
  description?: CmssyLocalized;
  /** Price net (minor units) - Net unit price in cents */
  price: number;
  /** Tax rate - VAT percent, e.g. 23 */
  taxRate?: number;
  /** Unit */
  unit?: "pcs" | "set" | "m" | "kg" | "pair";
  /** Packaging - e.g. box of 10 */
  packaging?: string;
  /** Inventory */
  inventory?: number;
  /** Image */
  image?: CmssyMedia;
  /** Gallery */
  gallery?: CmssyMedia[];
  /** Specs */
  specs?: {
    /** Material */
    material?: string;
    /** Dimensions */
    dimensions?: string;
    /** Weight (kg) */
    weightKg?: number;
    /** Standard */
    standard?: string;
    /** Operating temperature */
    operatingTemp?: string;
  };
  /** Datasheet URL */
  datasheetUrl?: string;
}

export type ProductRecord = CmssyRecordOf<ProductData>;

/**
 * Service
 *
 * CMS-929 verification: second product source with its own field names.
 *
 * Model slug: `service`
 */
export interface ServiceData {
  /** Title */
  title: string;
  /** Net price */
  netPrice?: number;
  /** Code */
  code?: string;
  /** Available slots */
  slots?: number;
  /** Lead time (days) */
  leadDays?: number;
}

export type ServiceRecord = CmssyRecordOf<ServiceData>;

/**
 * Shop Member
 *
 * Site members who can sign in to the demo shop.
 *
 * Model slug: `shopmember`
 * Display field: `email`
 */
export interface ShopmemberData {
  /** Email */
  email: string;
  /** Password */
  password?: string;
  /** Name */
  name?: string;
  /** Contact name */
  contactName?: string;
  /** Company */
  company?: string;
  /** VAT ID */
  vatId?: string;
}

export type ShopmemberRecord = CmssyRecordOf<ShopmemberData>;

/** Every model in the workspace, by slug. */
export interface CmssyModels {
  category: CategoryData;
  product: ProductData;
  service: ServiceData;
  shopmember: ShopmemberData;
}

export type CmssyModelSlug = keyof CmssyModels;

/** The typed record list `public.model.records` returns for a model. */
export interface CmssyRecordList<Slug extends CmssyModelSlug> {
  items: Array<CmssyRecordOf<CmssyModels[Slug]>>;
  total: number;
  hasMore: boolean;
}
