
const en = {
  search: "Search",
  searchPlaceholder: "Search the catalog",
  searchAria: "Search the catalog",
  categoriesAria: "Categories",
  quickOrder: "Quick order",
  account: "Account",
  cart: "Cart",
  allCategories: "All categories",
  viewAllSkus: "View all {count} SKUs",
  topBrands: "Top brands",
  featured: "Featured",
  featuredBlurb: "Contract pricing and next-day dispatch on {name} lines.",
  browseCategory: "Browse {name}",

  inStock: "In stock",
  lowStock: "Low stock",
  backorder: "Backorder",
  outOfStock: "Out of stock",
  backorderTitle: "Currently on backorder",
  backorderBody:
    "You can backorder now - we'll dispatch as soon as stock lands and only invoice on dispatch.",
  backorderNow: "Backorder now",
  browseInStockAlternatives: "Browse in-stock alternatives",
  authPitchTitle: "The trade counter for industrial parts.",
  authPitchText:
    "48,000+ SKUs, contract pricing, credit terms and next-day dispatch - built for procurement teams.",
  statDispatch: "Dispatch",
  statCreditTerms: "Credit terms",
  statTradeAccounts: "Trade accounts",
  signInTab: "Sign in",
  requestTab: "Request account",
  signInTitle: "Sign in to your account",
  signInLead: "Use your trade account email and password.",
  requestAccountTitle: "Request a trade account",
  requestAccountLead:
    "We verify company details before activating credit terms - usually within one business day.",
  add: "Add",
  adding: "Adding...",
  from: "from",
  save: "save",
  netPer: "net /",

  category: "Category",
  allProducts: "All products",
  availability: "Availability",
  anyAvailability: "Any availability",
  brand: "Brand",
  anyBrand: "Any brand",
  sort: "Sort",
  sortName: "Name",
  sortPriceAsc: "Price, low to high",
  sortPriceDesc: "Price, high to low",
  activeFilters: "Active filters",
  removeFilter: "Remove filter",
  reset: "Reset",
  noProductsFound: "No products found",
  noProductsMatch: "No products match these filters",
  noProductsHint: "Try removing a filter - this combination returned nothing.",
  clearAllFilters: "Clear all filters",
  previous: "Previous",
  next: "Next",
  paginationAria: "Pagination",
  productsCountOne: "{count} product",
  productsCountMany: "{count} products",
  fromBrand: "from {brand}",
  pageOf: "Page {page} of {last}",
  searchEmptyHint:
    "We couldn't find anything matching \u201c{term}\u201d. Check the SKU, try a cross-reference number, or browse the category.",
  browseX: "Browse {what}",
  theCatalog: "the catalog",

  shop: "Shop",
  breadcrumbAria: "Breadcrumb",
  technicalData: "Technical data",
  material: "Material",
  dimensions: "Dimensions",
  weight: "Weight",
  standard: "Standard",
  operatingTemperature: "Operating temperature",
  unit: "Unit",
  volumePricing: "Volume pricing",
  quantity: "Quantity",
  unitPrice: "Unit price",
  lineTotalNet: "Line total (net)",
  datasheet: "Datasheet (PDF)",
  contractDiscount: "contract",
  inclVat: "incl. {rate}% VAT",
  packaging: "Packaging",
  addWithTotal: "Add - {total}",
  goToCartAdded: "Go to cart ({count} added)",
  added: "Added",

  cartEmpty: "Your cart is empty.",
  browseCatalog: "Browse the catalog",
  closeCart: "Close the cart",
  dismiss: "Dismiss",
  itemOne: "item",
  itemMany: "items",
  qty: "Qty",
  netSubtotal: "Net subtotal",
  totalGross: "Total gross",
  goToCheckout: "Go to checkout",
  continueShopping: "Continue shopping",
  addedToCart: "Added to cart",
  remove: "Remove",
  netEach: "net each",
  volumePriceApplied: "Volume price at {minQty}+ applied",
  quantityFor: "Quantity for {name}",

  cartAndCheckout: "Cart and checkout",
  deliveryAddress: "Delivery address",
  email: "Email",
  password: "Password",
  contactName: "Contact name",
  company: "Company",
  streetAndNumber: "Street and number",
  addressLine2: "Address line 2",
  postalCode: "Postal code",
  city: "City",
  countryIso: "Country (ISO-2)",
  phone: "Phone",
  vatId: "VAT ID",
  poNumber: "PO number",
  noteForWarehouse: "Note for the warehouse",
  delivery: "Delivery",
  deliveryMethod: "Delivery method",
  selectAMethod: "Select a method",
  chooseDeliveryMethod: "Choose a delivery method to continue.",
  discountCode: "Discount code",
  apply: "Apply",
  subtotalNet: "Subtotal (net)",
  discount: "Discount",
  totalInclVat: "Total (incl. VAT)",
  netTotal: "Net total",
  placeOrder: "Place order",
  placingOrder: "Placing order...",
  checkoutFailed: "Checkout failed",

  tradeAccount: "Trade account",
  tradeSignIn: "Trade sign in",
  openTradeAccount: "Open a trade account",
  signIn: "Sign in",
  signOut: "Sign out",
  createAccount: "Create account",
  needAnAccount: "Need an account? Register",
  haveAnAccount: "Already have an account? Sign in",
  signedInAs: "Signed in as",
  orderHistory: "Order history",
  loadingOrders: "Loading orders...",
  noOrdersYet: "No orders yet.",
  couldNotSignIn: "Could not sign in",

  loadingOrder: "Loading the order...",
  orderNotAvailable: "Order not available",
  orderNotAvailableHint:
    "Sign in with the account that placed this order, or open the confirmation link from your email.",
  goToAccount: "Go to account",
  backToOrders: "Back to orders",
  orderNotFound: "Order not found",
  orderLinkExpired:
    "This confirmation link is invalid or has expired. Sign in to see the order in your account.",
  orderPlaced: "Order placed",
  order: "Order",
  note: "Note",
  downloadInvoice: "Download invoice",
  keepThisLink:
    "Keep this link - it is the only way back to this order without an account.",
  orderConfirmation: "Order confirmation",
  awaitingPayment: "Awaiting payment · net 30",
  partiallyPaid: "Partially paid",
  paid: "Paid",
  refunded: "Refunded",
  po: "PO",
  confirmationSentTo: "confirmation sent to",

  quickOrderIntro:
    "Paste a list of SKUs and quantities. Volume breaks apply automatically.",
  quickOrderHint: "One SKU and quantity per line",
  addAllToCart: "Add all to cart",
  addingLines: "Adding lines...",
  product: "Product",
  status: "Status",
  skuNotFound: "SKU not found",
  couldNotAdd: "Could not add",
  quickOrderSummary: "{added} of {total} lines added to cart",
  notFoundTitle: "Page not found",
  notFoundBody: "The page you're looking for doesn't exist or has moved.",
  backToCatalog: "Back to catalog",
  statusPayment: "Payment",
  statusFulfilment: "Fulfilment",
  statusTracking: "Tracking",
  noTrackingYet: "No tracking yet",
  fulfilmentFulfilled: "Dispatched",
  fulfilmentProcessing: "Processing",
  fulfilmentUnfulfilled: "Not fulfilled",
  statusHistory: "Status history",
  timelinePlaced: "Order placed",
  timelinePaid: "Payment received",
  timelineDispatched: "Dispatched",
  timelinePending: "Pending",

  productNotFound: "Product not found",
  by: "by",
} as const;

export type ShopCopy = Record<keyof typeof en, string>;

const no: ShopCopy = {
  search: "Søk",
  searchPlaceholder: "Søk i katalogen",
  searchAria: "Søk i katalogen",
  categoriesAria: "Kategorier",
  quickOrder: "Hurtigbestilling",
  account: "Konto",
  cart: "Handlekurv",
  allCategories: "Alle kategorier",
  viewAllSkus: "Se alle {count} varenumre",
  topBrands: "Toppmerker",
  featured: "Anbefalt",
  featuredBlurb: "Avtalepriser og levering neste dag p\u00e5 {name}.",
  browseCategory: "Se {name}",

  inStock: "På lager",
  lowStock: "Lav beholdning",
  backorder: "Restordre",
  outOfStock: "Utsolgt",
  backorderTitle: "For øyeblikket i restordre",
  backorderBody:
    "Du kan bestille i restordre nå - vi sender så snart varen er på lager og fakturerer først ved forsendelse.",
  backorderNow: "Bestill i restordre",
  browseInStockAlternatives: "Se alternativer på lager",
  authPitchTitle: "Handelsdisken for industrideler.",
  authPitchText:
    "48 000+ varenumre, kontraktspriser, kredittvilkår og neste-dags forsendelse - laget for innkjøpsteam.",
  statDispatch: "Forsendelse",
  statCreditTerms: "Kredittvilkår",
  statTradeAccounts: "Bedriftskontoer",
  signInTab: "Logg inn",
  requestTab: "Søk om konto",
  signInTitle: "Logg inn på kontoen din",
  signInLead: "Bruk e-post og passord for bedriftskontoen din.",
  requestAccountTitle: "Søk om en bedriftskonto",
  requestAccountLead:
    "Vi verifiserer firmaopplysninger før vi aktiverer kredittvilkår - vanligvis innen én virkedag.",
  add: "Legg til",
  adding: "Legger til...",
  from: "fra",
  save: "spar",
  netPer: "netto /",

  category: "Kategori",
  allProducts: "Alle produkter",
  availability: "Tilgjengelighet",
  anyAvailability: "All tilgjengelighet",
  brand: "Merke",
  anyBrand: "Alle merker",
  sort: "Sortering",
  sortName: "Navn",
  sortPriceAsc: "Pris, lav til høy",
  sortPriceDesc: "Pris, høy til lav",
  activeFilters: "Aktive filtre",
  removeFilter: "Fjern filter",
  reset: "Nullstill",
  noProductsFound: "Ingen produkter funnet",
  noProductsMatch: "Ingen produkter passer disse filtrene",
  noProductsHint: "Prøv å fjerne et filter - denne kombinasjonen ga ingenting.",
  clearAllFilters: "Fjern alle filtre",
  previous: "Forrige",
  next: "Neste",
  paginationAria: "Paginering",
  productsCountOne: "{count} produkt",
  productsCountMany: "{count} produkter",
  fromBrand: "fra {brand}",
  pageOf: "Side {page} av {last}",
  searchEmptyHint:
    "Vi fant ingenting som matcher \u201c{term}\u201d. Sjekk varenummeret, prøv et kryssreferansenummer, eller bla i kategorien.",
  browseX: "Se {what}",
  theCatalog: "katalogen",

  shop: "Butikk",
  breadcrumbAria: "Brødsmuler",
  technicalData: "Tekniske data",
  material: "Materiale",
  dimensions: "Mål",
  weight: "Vekt",
  standard: "Standard",
  operatingTemperature: "Driftstemperatur",
  unit: "Enhet",
  volumePricing: "Kvantumsrabatt",
  quantity: "Antall",
  unitPrice: "Enhetspris",
  lineTotalNet: "Linjesum (netto)",
  datasheet: "Datablad (PDF)",
  contractDiscount: "avtalepris",
  inclVat: "inkl. {rate}% mva.",
  packaging: "Pakning",
  addWithTotal: "Legg til - {total}",
  goToCartAdded: "Gå til handlekurven ({count} lagt til)",
  added: "Lagt til",

  cartEmpty: "Handlekurven er tom.",
  browseCatalog: "Se katalogen",
  closeCart: "Lukk handlekurven",
  dismiss: "Lukk",
  itemOne: "vare",
  itemMany: "varer",
  qty: "Ant.",
  netSubtotal: "Delsum netto",
  totalGross: "Totalt brutto",
  goToCheckout: "Gå til kassen",
  continueShopping: "Fortsett å handle",
  addedToCart: "Lagt i handlekurven",
  remove: "Fjern",
  netEach: "netto per stk",
  volumePriceApplied: "Kvantumspris fra {minQty}+ brukt",
  quantityFor: "Antall for {name}",

  cartAndCheckout: "Handlekurv og kasse",
  deliveryAddress: "Leveringsadresse",
  email: "E-post",
  password: "Passord",
  contactName: "Kontaktperson",
  company: "Firma",
  streetAndNumber: "Gate og nummer",
  addressLine2: "Adresselinje 2",
  postalCode: "Postnummer",
  city: "Sted",
  countryIso: "Land (ISO-2)",
  phone: "Telefon",
  vatId: "MVA-nummer",
  poNumber: "Bestillingsnummer (PO)",
  noteForWarehouse: "Melding til lageret",
  delivery: "Levering",
  deliveryMethod: "Leveringsmåte",
  selectAMethod: "Velg en leveringsmåte",
  chooseDeliveryMethod: "Velg en leveringsmåte for å fortsette.",
  discountCode: "Rabattkode",
  apply: "Bruk",
  subtotalNet: "Delsum (netto)",
  discount: "Rabatt",
  totalInclVat: "Totalt (inkl. mva.)",
  netTotal: "Sum netto",
  placeOrder: "Send bestilling",
  placingOrder: "Sender bestilling...",
  checkoutFailed: "Bestillingen mislyktes",

  tradeAccount: "Bedriftskonto",
  tradeSignIn: "Logg inn (bedrift)",
  openTradeAccount: "Opprett bedriftskonto",
  signIn: "Logg inn",
  signOut: "Logg ut",
  createAccount: "Opprett konto",
  needAnAccount: "Ingen konto? Registrer deg",
  haveAnAccount: "Har du allerede konto? Logg inn",
  signedInAs: "Logget inn som",
  orderHistory: "Ordrehistorikk",
  loadingOrders: "Laster bestillinger...",
  noOrdersYet: "Ingen bestillinger ennå.",
  couldNotSignIn: "Kunne ikke logge inn",

  loadingOrder: "Laster bestillingen...",
  orderNotAvailable: "Bestillingen er ikke tilgjengelig",
  orderNotAvailableHint:
    "Logg inn med kontoen som la inn bestillingen, eller åpne bekreftelseslenken fra e-posten din.",
  goToAccount: "Gå til konto",
  backToOrders: "Tilbake til bestillinger",
  orderNotFound: "Fant ikke bestillingen",
  orderLinkExpired:
    "Denne bekreftelseslenken er ugyldig eller utløpt. Logg inn for å se bestillingen på kontoen din.",
  orderPlaced: "Bestilling sendt",
  order: "Bestilling",
  note: "Melding",
  downloadInvoice: "Last ned faktura",
  keepThisLink:
    "Ta vare på denne lenken - den er eneste vei tilbake til bestillingen uten konto.",
  orderConfirmation: "Ordrebekreftelse",
  awaitingPayment: "Avventer betaling · netto 30",
  partiallyPaid: "Delvis betalt",
  paid: "Betalt",
  refunded: "Refundert",
  po: "PO",
  confirmationSentTo: "bekreftelse sendt til",

  quickOrderIntro:
    "Lim inn en liste med varenumre og antall. Kvantumsrabatter beregnes automatisk.",
  quickOrderHint: "Ett varenummer og antall per linje",
  addAllToCart: "Legg alt i handlekurven",
  addingLines: "Legger til linjer...",
  product: "Produkt",
  status: "Status",
  skuNotFound: "Fant ikke varenummer",
  couldNotAdd: "Kunne ikke legge til",
  quickOrderSummary: "{added} av {total} linjer lagt i handlekurven",
  notFoundTitle: "Siden finnes ikke",
  notFoundBody: "Siden du leter etter finnes ikke eller er flyttet.",
  backToCatalog: "Tilbake til katalogen",
  statusPayment: "Betaling",
  statusFulfilment: "Levering",
  statusTracking: "Sporing",
  noTrackingYet: "Ingen sporing ennå",
  fulfilmentFulfilled: "Sendt",
  fulfilmentProcessing: "Behandles",
  fulfilmentUnfulfilled: "Ikke levert",
  statusHistory: "Statushistorikk",
  timelinePlaced: "Bestilling lagt inn",
  timelinePaid: "Betaling mottatt",
  timelineDispatched: "Sendt",
  timelinePending: "Venter",

  productNotFound: "Fant ikke produktet",
  by: "fra",
};

const dictionaries: Record<string, ShopCopy> = { en, no };

export function copyFor(locale: string): ShopCopy {
  return dictionaries[locale] ?? en;
}

export function fill(
  template: string,
  values: Record<string, string | number>,
): string {
  return template.replace(/\{(\w+)\}/g, (match, key) =>
    key in values ? String(values[key]) : match,
  );
}
